### ISSUE TITLE
Make services have a structured hierarchy

### ISSUE THREAD

**Issue by ninjaboynaru** [eXigentCoder/krpc-node#13]
Having to manauly get the id of the class you want and then pass it to a call is cumbersome.
```
let response = await client.send(spaceCenter.getActiveVessel());  
let vesselId = response.results[0].value;  
response = await client.send(spaceCenter.vesselGetControl(vesselId));
```
Something like this would be better
```
let vessel = await client.services.spaceCenter.activeVessel;
let control = await vessel.control;
control.sas = true;
```
_I understand this removes the ability to batch send calls._

It has already been implemented in [here](https://github.com/lucaelin/krpc.js). I'd be happy to give it a shot and submit a pull request?

**Comment by eXigentCoder** [comment]
I really like the updated syntax that @lucaelin has used there. If possible I'd like the option to keep the existing `client.send([...])` functionality for backwards compatibility and for the case where a person may want to send multiple requests to the server at one time. I think there may be a way to have the best of both worlds and will try some things from my side.

If you are interested you are welcome to take a look as well, I'd be happy to take a look at a PR. If it turns out it's not possible to support both ways without a breaking change, we can look at incrementing the major version number and supporting both pieces of functionality that way.

**Comment by eXigentCoder** [comment]
Have started a  taking a stab at it in this branch https://github.com/eXigentCoder/krpc-node/tree/direct-call-invocation

**Comment by ninjaboynaru** [comment]
Awesome. I'll take a look at it in a few hours.

**Comment by eXigentCoder** [comment]
Manged to make quite a bit of headway with it, can see it working with this test: https://github.com/eXigentCoder/krpc-node/blob/direct-call-invocation/test/api/direct-invocation.js
It still needs quite a bit of a clean up, and I'm thinking of changing how the responses get returned when invoked in this way but it's late here, so going to get some sleep!

**Comment by ninjaboynaru** [comment]
I looked it over. Looks like a good start. I could not get anything done today, but I'm thinking of popper getters and setters **_(instead of having to do control.get())_** and a better way of obtaining the result of a direct calls **_(instead of having to do results[0].value)_**.

I'll throw something in tomorrow (I'm completely free)

**Comment by ninjaboynaru** [comment]
Hay

**Comment by ninjaboynaru** [comment]
## Getters and Setters
I replaced `class.get()` and `class.set()` with built in getters and setters. [Link](https://github.com/ninjaboynaru/krpc-node/commit/3dddb545a6646a086f58f9fc4e430a0c86078827)  

## Easier responses
I also changed how responses are returned when using direct invocation. [Link](https://github.com/ninjaboynaru/krpc-node/commit/a87d5f781e43f219268376a08810548afeac47c4).  

## Misc and Notes
The downside of using getters and setters is that you can not await for a setter call to complete. Maybe the original system of using `.set()` is better.   

Instead of having to call `response.results[0].value`, a direct response call will now simply just return the value. And if `response.results[0]` contains an error, then that error will be thrown, though my current formatting of the error may not be very informative.

**Comment by eXigentCoder** [comment]
I really like the easier response option, I'm going to give some thought to if this should be the default behaviour for calling methods in the old way as well. Of course that might break existing functionality and result in a major version bump but could be controlled with a options flag when making the client. Will pull your code in a bit later today, thanks!

For a variety of reasons (see below) I'm not a fan of the ES6 class keyword and it's associated getters and setters. Another difficulty with the getters and setters is they seem to prevent you from being able to pass the associated function around for later execution. I think the downsides outway the conciseness they bring.

[Why Composition is Harder with Classes](https://medium.com/javascript-scene/why-composition-is-harder-with-classes-c3e627dcd0aa)
[How to Fix the ES6 `class` keyword](https://medium.com/javascript-scene/how-to-fix-the-es6-class-keyword-2d42bb3f4caf)
[JavaScript Factory Functions vs Constructor Functions vs Classes](https://medium.com/javascript-scene/javascript-factory-functions-vs-constructor-functions-vs-classes-2f22ceddf33e)

**Comment by parkerbossier** [comment]
I've been playing around with adding top level classes like Vessel and World. This way, I can do things like this (note that I'm in TypeScript)...

`const world = await World.create(client);
	const vessel = await world.getActiveVessel();
	await vessel.autoPilotSetSasMode(SASMode.StabilityAssist);
	await vessel.setTranslation(1, 1, 1, 1);
	await vessel.stage();`

And some sample Vessel code is...
`export class Vessel {
	static async create(client: Client, id: number) {
		const [autoPilot, control] = (await client.send<Result.Id, Result.Id>(
			[
				spaceCenter.vesselGetAutoPilot(id),
				spaceCenter.vesselGetControl(id)
			]
		)).results;

		const vessel = new Vessel(autoPilot.value, client, control.value, id);
		return vessel;
	}

	private constructor(
		private autoPilot: number,
		private client: Client,
		private control: number,
		public id: number
	) { }

	async setThrottle(throttle: number) {
		await this.client.send(
			spaceCenter.controlSetThrottle(this.control, throttle)
		);
	}
}`

I'm liking this approach so far, as it bring a new level of class organization while retaining the ability to batch RPC calls and such. Any thoughts on this approach? I'm thinking about eventually publishing this as a separate package that depends on krpc-node, although I'm certainly open to consolidating here if applicable.

**Comment by parkerbossier** [comment]
Also, awesome repo! I'm so happy I can use krpc with Node. I don't want to use C# or Lua or any of the other offerings in the standard krpc mod.

**Comment by eXigentCoder** [comment]
@parkerbossier So glad you are enjoying the module, and thank you for your input!

I'm just about to publish the changes for the object hierarchy and bump the major version number. After that I'm going to close this issue, would you mind taking a look at the code (Have updated examples in the README.md file) and see how this would fit in with your TS implementation?

**Comment by eXigentCoder** [comment]
[Version 4.0.0](https://www.npmjs.com/package/krpc-node) is now on the repo, please feel free take a look and let me know what you think!

**Comment by parkerbossier** [comment]
This looks cool! I'm still definitely writing a Vessel TypeScript class to add type safe helpers for things like setting up streams and things, but it looks like it now might be worth it to write up a module type def for the new object hierarchy setup. Have you used or do you want to use TypeScript at all?

**Comment by parkerbossier** [comment]
Just dropping by to say that things are MUCH EASIER now. Thanks for this :)

**Comment by eXigentCoder** [comment]
So glad you are enjoying the update!
I have used TypeScript briefly and I'm not a big fan, [Eric Elliott has put my feelings into words already.](https://medium.com/javascript-scene/you-might-not-need-typescript-or-static-types-aa7cb670a77b)
That being said, I'm not opposed to including the type definitions in the module, as long as I can still write code in plain JS. Ideally the definitions for the services would be generated in the same way the services themselves are generated.
If that's not possible, I think it would be great if I could put a link in the `README.md` to your work to help people out?
