### ISSUE TITLE
Error: illegal token '<' (/krpc.proto, line 1)

### ISSUE THREAD

**Issue by Somfic** [eXigentCoder/krpc-node#30]
Hi, I'm having trouble getting started with this library. Whatever I do, I always get this error:

![image](https://user-images.githubusercontent.com/29230467/115960555-6193c280-a512-11eb-84c5-e844f556dae7.png)

My current code is just the `createClient` function

**Comment by Sam-Neale** [comment]
Taking a guess, but I believe the issue to be that it can't find that file and is rendering a 404 page (which has HTML)
